levelkdev/futarchy-app

app/App.js
app/actions/index.js
app/components/DecisionMarket.js
app/components/DecisionMarketList.js
app/containers/ActiveDecisionMarketList.js
app/containers/CreateDecisionMarket.js
app/main.js
app/reducers/decisionMarkets.js
app/reducers/index.js
app/script.js
contracts/StubFutarchyApp.sol
package-lock.json
package.json

try running it, clicking the button to create a decision should create the decision in a "pending" state .. when the transaction succeeds the pending state is removed and the decision is rendered on the UI

add redux and actions/reducers to handle state for a decisions list

---

app/App.js
app/components/AppHeader.js
app/containers/AppHeaderContainer.js
app/containers/DecisionSummaryContainer.js
app/icons/LeftArrow.js
app/views/DecisionDetail.js

so we can display data related to the current decision view, like the "question" metadata

add router and app state to the App header

---

app/actions/index.js
app/client/MiniMeToken.js
app/client/index.js
app/reducers/initDataProps.js
contracts/Futarchy.sol
package-lock.json
package.json
scripts/deploy_deps.js

Adds a step to approve the token transfer for market funding from the user address to the Futarchy contract address, so the `newDecision` transaction can succeed

New decision with token approval

---

app/components/AppHeader.js

fix import in AppHeader component to use the correct case

---

contracts/Futarchy.sol
test/app.js

Function to allow us to set the outcome of the price oracle.  Will add a script to set the outcome of the price oracle in another PR.

setPriceOutcome function

---

package.json
scripts/set_data/price.js

Script for setting price on the price oracle.  Takes the DAO address, decision id, and price as arguments.
Also added a compile:truffle command to package.json :)

script for setting price on price oracle

---

app/App.js
app/actions/index.js
app/client/index.js
app/components/PerformanceSummary.js
app/containers/PerformanceSummaryContainer.js
app/middleware/appEventInterceptor.js
app/reducers/computed/tradesByAccount.js
app/reducers/computed/tradesByAccount.test.js
app/reducers/index.js
app/reducers/performance.js
app/reducers/performance.test.js
app/reducers/trades.js
app/reducers/trades.test.js
app/views/Account.js
app/views/Home.js
contracts/Futarchy.sol
package-lock.json
package.json
test/Futarchy.test.js

Calculate the gain/loss based on user balance and current market prices. Display the raw gain/loss data on a temporary view

Gain loss calcs

---

app/App.js
app/components/AppHeader.js
app/views/ClosedDecisions.js
package-lock.json

Basic tab based Navigation using React Router. Aragon has a UI Component called TabBar but I couldn't get it to work with React Router. Styles are basically copied over from the Aragon UI TabBar component

Add Tab Navigation

---

app/actions/index.js
app/client/index.js
app/middleware/appEventInterceptor.js
app/reducers/decisionBalances.js
app/reducers/decisionBalances.test.js
app/reducers/index.js
app/util/traderDecisionHash.js
app/util/traderDecisionHash.test.js

fetch balances on each decision for the current account

---

app/components/MakePredictionForm.js

I changed the layout of this panel quite a bit from the mockups. The multiple steps in the original design of the form seemed unnecessary given the amount of space we have in this panel now that the description is gone.
This is only the style updates, nothing is hooked up yet. Interested to hear what you all think…

Update prediction form styles

---

app/components/DecisionCard.js
app/components/DecisionList.js
app/components/MakePredictionForm.js
app/components/MarketCircles.js

Style updates to:
- Make Prediction Form
- Market Circles
- Decision Card

Misc style updates

---

app/public/images/icon.svg

So I can't actually get the app icon to show up :/ it's structured just like the other app icons ie https://github.com/aragon/aragon-apps/tree/master/apps/voting
Hoping someone can test this branch and see if it shows up on their end?

Add Futarchy app icon

---

app/components/MarketCircles.js
app/containers/MarketCirclesContainer.js

Changes the losing market circle fill color to light gray and draws a diagonal line across it

Add losing state to market circle

---

app/client/index.js
contracts/Futarchy.sol
test/Futarchy.test.js

@emaG3m hope this helps us stay under the gas limit for deployment

Remove passthrough functions

---

app/actions/index.js
app/client/index.js
app/components/MakePredictionForm.js
app/containers/MakePredictionFormContainer.js
app/middleware/appEventInterceptor.js
app/reducers/decisionMarkets.js
app/util/calcOutcomeTokenCount.js
app/util/calcOutcomeTokenPurchaseAmounts.js
app/util/decimalToWeiInt.js
app/util/pmJS/calcOutcomeTokenCount.js
contracts/Futarchy.sol
test/Futarchy.test.js

Hooks up the "make prediction" side panel so that we can execute market buys from the UI

Make prediction feature

---

package-lock.json
package.json

to avoid the dependency graph bug that happens with newer versions, make sure our app is using this version

add truffle-flattener dependency

---

app/components/MarketCircles.js
app/containers/MarketCirclesContainer.js

Instead of the decision.resolved
Fixes: https://github.com/levelkdev/futarchy-app/issues/66

Use decision status to determine market winner

---

app/components/TradeList.js

Formats trade time into human readable form
Fixes spacing issues so table doesn’t scroll horizontally anymore
Fixes: https://github.com/levelkdev/futarchy-app/issues/72

TradeList style updates

---

app/components/MarketCircles.js

Fixes the issue where both Yes and No could be displayed as losing

Fix Yes market circle display state

---

.env
README.md
app/client/contractCall.js
app/client/contractFn.js
app/client/index.js
app/main.js
app/script.js
app/util/logger.js
package.json

Get rid of console logs, create "debug mode"

---

app/actions/index.js
app/components/ClaimReturnsForm.js
app/components/GainLossPercentageDisplay.js
app/components/MakePredictionForm.js
app/components/MarketCircles.js
app/components/decisionTables/ClosedDecisionsTable.js
app/components/decisionTables/DecisionResultCell.js
app/components/decisionTables/PredictedPricesCell.js
app/components/decisionTables/QuestionLinkCell.js
app/components/decisionTables/ResolvedDecisionsTable.js
app/components/decisionTables/SingleGainLossPercentageCell.js
app/components/decisionTables/TimeframeCell.js
app/containers/DecisionPredictedPricesContainer.js
app/containers/DecisionQuestionLinkContainer.js
app/containers/DecisionResultContainer.js
app/containers/DecisionWinningMarketGainLossContainer.js
app/containers/DecisionWinningMarketReturnsContainer.js
app/containers/MarketCirclesContainer.js
app/reducers/computed/getWinningMarket.js
app/reducers/computed/getWinningMarket.test.js
app/reducers/decisionMarkets.js
app/reducers/decisionMarkets.test.js
app/test/mockDecision.js
scripts/seed_data/data/data_0.json
scripts/seed_data/seed.js

and add a computed `winningMarket` property for each decision to state, to use in all views

Show winning market results in "My Positions" view

---

app/components/MakePredictionForm.js
app/components/decisionTables/PredictedPricesCell.js

and remote the 'ETH' token from display

use predicted price value formatting everywhere

---

app/client/index.js
app/components/MakePredictionForm.js
app/util/numberToWei.js
app/util/toWei.js
package-lock.json
package.json

rather than relying on the global web3 instance since we aren't sure what version of web3 that will be

use web3-utils package for the `toWei` util function

---

app/components/MakePredictionForm.js
app/components/SuccessMetricDisplay.js
app/constants/outcomeTokenIndexes.js
app/constants/positions.js
app/containers/MakePredictionFormContainer.js
package-lock.json

Changed this a bit in an attempt to communicate to the user exactly what they are predicting/risking

Update the make prediction form field displays

---

app/App.js

fixes https://github.com/levelkdev/futarchy-app/issues/111

change aragon-ui publicURI to `./aragon-ui/`

---

app/components/CreateDecisionMarketForm.js
app/components/TokenSymbolDisplay.js
app/util/tokenSymbol.js

fixes https://github.com/levelkdev/futarchy-app/issues/104

Check balance for new decision issue104

---

app/actions/index.js
app/client/index.js
app/containers/MarketPricesLineChartContainer.js
app/middleware/appEventInterceptor.js
app/reducers/initDataProps.js
contracts/Futarchy.sol

use web3Eth function to get all data for the latest block, including timestamp

remove blocktime workaround from Futarchy.sol contract

---

app/components/MarketCircles.js

https://github.com/levelkdev/futarchy-app/issues/114

make circle text unselectable

---

package-lock.json
package.json

for aragon template repo compat

update to tidbit that renames SafeMath -> TidbitSafeMath

---

app/components/MakePredictionForm.js
contracts/Futarchy.sol

aragon client compat fix
